name: aurana
description: "spirit guide"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^5.3.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: 18.0.1
  timezone: ^0.9.4
  url_launcher: ^6.3.1
  http: ^1.3.0
  speech_to_text: ^7.0.0
  image_picker: ^0.8.7+3
  encrypt: ^5.0.3
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/tarot/
    - assets/images/parchment_background.png
    - assets/images/bg1.png
    - assets/images/bg2.png
    - assets/images/bg3.png
    - assets/images/bg4.png
    - assets/images/bg5.png
    - assets/images/bg6.png
    - assets/images/bg7.png
    - assets/images/bg8.png
    - assets/images/bg9.png
    - assets/images/bg10.png

  fonts:
    - family: CabinSketch
      fonts:
        - asset: assets/fonts/CabinSketch-Bold.ttf
        - asset: assets/fonts/CabinSketch-Regular.ttf
    - family: Whisper
      fonts:
        - asset: assets/fonts/Whisper-Regular.ttf
    - family: Ariana
      fonts:
        - asset: assets/fonts/ArianaViolet.ttf
    - family: Shade
      fonts:
        - asset: assets/fonts/ShadeBlue.ttf
    - family: Short
      fonts:
        - asset: assets/fonts/ShortBaby.ttf