name: aurana
description: "spirit guide"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^5.3.1
  shared_preferences: ^2.5.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  url_launcher: ^6.3.1
  http: ^0.13.6
  speech_to_text: ^7.0.0
  image_picker: ^1.1.2
  encrypt: ^5.0.3
  intl: ^0.20.2
  camera: ^0.10.0+4
  path_provider: ^2.0.14
  win32: ^5.5.3
  google_ml_kit: ^0.19.0 # Use the latest version available
  sqflite: ^2.2.0
  path: ^1.8.3
  fluttertoast: ^8.2.1
  share_plus: ^10.1.4
  flutter_animate: ^4.5.2
  confetti: ^0.7.0
  supabase_flutter: ^2.8.3
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.2.1
  font_awesome_flutter: ^10.4.0
  cached_network_image: ^3.2.3
  video_player: ^2.9.3
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  postgrest: ^2.1.0
  dart_openai: ^1.0.0
  audioplayers: ^5.2.0  # ✅ Add this line for sound playback
  flutter_launcher_icons: ^0.13.1
  in_app_purchase: ^3.1.7
  googleapis_auth: ^1.4.1
  swipable_stack: ^1.1.0
  shimmer: ^3.0.0
  geolocator: ^10.0.0
  geocoding: ^2.0.5
  flutter_tts: ^3.8.4
  realtime_client: ^2.4.2
  profanity_filter: ^2.0.0





flutter_icons:
  android: true
  ios: false  # ✅ This prevents any iOS changes
  image_path: "assets/aurana.png"  # ✅ Change this to your icon path
  adaptive_icon_foreground: "assets/aurana.png"
  adaptive_icon_background: "#000000"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/tarot/
    - assets/images/parchment_background.png
    - assets/images/bg1.png
    - assets/images/bg2.png
    - assets/images/bg3.png
    - assets/images/bg4.png
    - assets/images/bg5.png
    - assets/images/bg6.png
    - assets/images/bg7.png
    - assets/images/bg8.png
    - assets/images/bg9.png
    - assets/images/bg10.png
    - assets/images/bg0.png
    - assets/images/27.png
    - assets/images/30.png
    - assets/images/serv1.png
    - assets/images/profile.png
    - assets/model.tflite
    - .env
    - assets/default_avatar.png
    - assets/sounds/card_flip.mp3
    - assets/media/splash.gif
    - assets/images/guide.png
    - assets/images/aura.png
    - assets/images/home.png
    - assets/images/catcher.png
    - assets/images/misc.png
    - assets/images/misc2.png
    - assets/images/profile.png
    - assets/sounds/level_up.mp3
    - assets/sounds/friend_accepted.mp3
    - assets/sounds/aurana_tranquil.mp3
    - assets/zodiac/aries.png
    - assets/zodiac/taurus.png
    - assets/zodiac/gemini.png
    - assets/zodiac/cancer.png
    - assets/zodiac/leo.png
    - assets/zodiac/virgo.png
    - assets/zodiac/libra.png
    - assets/zodiac/scorpio.png
    - assets/zodiac/sagittarius.png
    - assets/zodiac/capricorn.png
    - assets/zodiac/aquarius.png
    - assets/zodiac/pisces.png
    - assets/images/default_avatar.png
    - assets/images/yinyang.png
    - assets/images/champagne_bottle.png
    - assets/images/tarot/ace-of-cups-gilded-tarot.png
    - assets/images/tarot/ace-of-pentacles-gilded-tarot.png
    - assets/images/tarot/ace-of-swords-gilded-tarot.png
    - assets/images/tarot/ace-of-wands-gilded-tarot.png
    - assets/images/tarot/eight-of-cups-gilded-tarot.png
    - assets/images/tarot/eight-of-pentacles-gilded-tarot.png
    - assets/images/tarot/eight-of-swords-gilded-tarot.png
    - assets/images/tarot/eight-of-wands-gilded-tarot.png
    - assets/images/tarot/five-of-cups-gilded-tarot.png
    - assets/images/tarot/five-of-pentacles-gilded-tarot.png
    - assets/images/tarot/five-of-swords-gilded-tarot.png
    - assets/images/tarot/five-of-wands-gilded-tarot.png
    - assets/images/tarot/four-of-cups-gilded-tarot.png
    - assets/images/tarot/four-of-pentacles-gilded-tarot.png
    - assets/images/tarot/four-of-swords-gilded-tarot.png
    - assets/images/tarot/four-of-wands-gilded-tarot.png
    - assets/images/tarot/king-of-cups-gilded-tarot.png
    - assets/images/tarot/king-of-pentacles-gilded-tarot.png
    - assets/images/tarot/king-of-swords-gilded-tarot.png
    - assets/images/tarot/king-of-wands-gilded-tarot.png
    - assets/images/tarot/knight-of-cups-gilded-tarot.png
    - assets/images/tarot/knight-of-pentacles-gilded-tarot.png
    - assets/images/tarot/knight-of-swords-gilded-tarot.png
    - assets/images/tarot/knight-of-wands-gilded-tarot.png
    - assets/images/tarot/nine-of-cups-gilded-tarot.png
    - assets/images/tarot/nine-of-pentacles-gilded-tarot.png
    - assets/images/tarot/nine-of-swords-gilded-tarot.png
    - assets/images/tarot/nine-of-wands-gilded-tarot.png
    - assets/images/tarot/page-of-cups-gilded-tarot.png
    - assets/images/tarot/page-of-pentacles-gilded-tarot.png
    - assets/images/tarot/page-of-swords-gilded-tarot.png
    - assets/images/tarot/page-of-wands-gilded-tarot.png
    - assets/images/tarot/queen-of-cups-gilded-tarot.png
    - assets/images/tarot/queen-of-pentacles-gilded-tarot.png
    - assets/images/tarot/queen-of-swords-gilded-tarot.png
    - assets/images/tarot/queen-of-wands-gilded-tarot.png
    - assets/images/tarot/seven-of-cups-gilded-tarot.png
    - assets/images/tarot/seven-of-pentacles-gilded-tarot.png
    - assets/images/tarot/seven-of-swords-gilded-tarot.png
    - assets/images/tarot/seven-of-wands-gilded-tarot.png
    - assets/images/tarot/six-of-cups-gilded-tarot.png
    - assets/images/tarot/six-of-pentacles-gilded-tarot.png
    - assets/images/tarot/six-of-swords-gilded-tarot.png
    - assets/images/tarot/six-of-wands-gilded-tarot.png
    - assets/images/tarot/ten-of-cups-gilded-tarot.png
    - assets/images/tarot/ten-of-pentacles-gilded-tarot.png
    - assets/images/tarot/ten-of-swords-gilded-tarot.png
    - assets/images/tarot/ten-of-wands-gilded-tarot.png
    - assets/images/tarot/the-chariot-gilded-tarot.png
    - assets/images/tarot/the-death-gilded-tarot.png
    - assets/images/tarot/the-devil-gilded-tarot-card.png
    - assets/images/tarot/the-emperor-gilded-tarot.png
    - assets/images/tarot/the-empress-gilded-tarot.png
    - assets/images/tarot/the-fool-gilded-tarot.png
    - assets/images/tarot/the-hanging-man-gilded-tarot.png
    - assets/images/tarot/the-hermit-gilded-tarot.png
    - assets/images/tarot/the-hierophant-gilded-tarot.png
    - assets/images/tarot/the-high-priestess-gilded-tarot.png
    - assets/images/tarot/the-judgement-gilded-tarot.png
    - assets/images/tarot/the-justice-gilded-tarot.png
    - assets/images/tarot/the-lovers-gilded-tarot.png
    - assets/images/tarot/the-magician-gilded-tarot.png
    - assets/images/tarot/the-moon-gilded-tarot.png
    - assets/images/tarot/the-star-gilded-tarot.png
    - assets/images/tarot/the-strength-gilded-tarot.png
    - assets/images/tarot/the-sun-gilded-tarot.png
    - assets/images/tarot/the-temperance-gilded-tarot.png
    - assets/images/tarot/the-tower-gilded-tarot.png
    - assets/images/tarot/the-wheel-of-fortune-gilded-tarot.png
    - assets/images/tarot/the-world-gilded-tarot.png
    - assets/images/tarot/three-of-cups-gilded-tarot.png
    - assets/images/tarot/three-of-pentacles-gilded-tarot.png
    - assets/images/tarot/three-of-swords-gilded-tarot.png
    - assets/images/tarot/three-of-wands-gilded-tarot.png
    - assets/images/tarot/two-of-cups-gilded-tarot.png
    - assets/images/tarot/two-of-pentacles-gilded-tarot.png
    - assets/images/tarot/two-of-swords-gilded-tarot.png
    - assets/images/tarot/two-of-wands-gilded-tarot.png
    - assets/images/osho zen/ace-of-clouds-osho-zen.png
    - assets/images/osho zen/ace-of-fire-wallpaper.png
    - assets/images/osho zen/ace-of-rainbows-osho-zen.png
    - assets/images/osho zen/ace-of-water-osho-zen.png
    - assets/images/osho zen/beyond-illusion-osho-zen.png
    - assets/images/osho zen/condition-osho-zen.png
    - assets/images/osho zen/creativity-osho-zen-tarot.png
    - assets/images/osho zen/eight-of-clouds-osho-zen.png
    - assets/images/osho zen/eight-of-fire-osho-zen.png
    - assets/images/osho zen/eight-of-rainbows-osho-zen.png
    - assets/images/osho zen/eight-of-water-osho-zen.png
    - assets/images/osho zen/existence-osho-zen-wallpaper.png
    - assets/images/osho zen/five-of-clouds-osho-zen.png
    - assets/images/osho zen/five-of-fire-osho-zen.png
    - assets/images/osho zen/five-of-rainbows-osho-zen.png
    - assets/images/osho zen/five-of-water-osho-zen.png
    - assets/images/osho zen/four-of-clouds-osho-zen.png
    - assets/images/osho zen/four-of-fire-osho-zen.png
    - assets/images/osho zen/four-of-rainbows-osho-zen.png
    - assets/images/osho zen/four-of-water-osho-zen.png
    - assets/images/osho zen/inner-voice-osho-zen-tarot.png
    - assets/images/osho zen/innocence-osho-zen.png
    - assets/images/osho zen/integration-osho-zen.png
    - assets/images/osho zen/king-of-clouds.png
    - assets/images/osho zen/king-of-fire-osho-zen.png
    - assets/images/osho zen/king-of-rainbows-osho-zen.png
    - assets/images/osho zen/king-of-water-osho-zen.png
    - assets/images/osho zen/knight-of-clouds-osho-zen.png
    - assets/images/osho zen/knight-of-fire-osho-zen.png
    - assets/images/osho zen/knight-of-rainbows-osho-zen.png
    - assets/images/osho zen/knight-of-water-osho-zen.png
    - assets/images/osho zen/new-vision-osho-zen.png
    - assets/images/osho zen/nine-of-clouds-osho-zen.png
    - assets/images/osho zen/nine-of-fire-osho-zen.png
    - assets/images/osho zen/nine-of-rainbow-osho-zen.png
    - assets/images/osho zen/nine-of-water-osho-zen.png
    - assets/images/osho zen/no-thingness-osho-zen.png
    - assets/images/osho zen/page-of-clouds-osho-zen.png
    - assets/images/osho zen/page-of-fire-osho-zen.png
    - assets/images/osho zen/page-of-rainbows-osho-zen.png
    - assets/images/osho zen/page-of-water-osho-zen.png
    - assets/images/osho zen/past-lives-osho-zen.png
    - assets/images/osho zen/projections-osho-zen.png
    - assets/images/osho zen/queen-of-clouds-osho-zen.png
    - assets/images/osho zen/queen-of-fire-osho-zen.png
    - assets/images/osho zen/queen-of-rainbows-osho-zen.png
    - assets/images/osho zen/queen-of-water-osho-zen.png
    - assets/images/osho zen/seven-of-clouds-osho-zen.png
    - assets/images/osho zen/seven-of-fire-osho-zen.png
    - assets/images/osho zen/seven-of-rainbows-osho-zen.png
    - assets/images/osho zen/six-of-clouds-osho-zen.png
    - assets/images/osho zen/six-of-fire-osho-zen.png
    - assets/images/osho zen/six-of-rainbows-osho-zen.png
    - assets/images/osho zen/six-of-water-osho-zen.png
    - assets/images/osho zen/ten-of-clouds-osho-zen.png
    - assets/images/osho zen/ten-of-fire-osho-zen.png
    - assets/images/osho zen/ten-of-rainbows-osho-zen.png
    - assets/images/osho zen/ten-of-water-osho-zen.png
    - assets/images/osho zen/the-aloneness-osho-zen.png
    - assets/images/osho zen/the-awareness-osho-zen.png
    - assets/images/osho zen/the-breakthrough-osho-zen.png
    - assets/images/osho zen/the-change-osho-zen.png
    - assets/images/osho zen/the-completion-osho-zen.png
    - assets/images/osho zen/the-courage-osho-zen.png
    - assets/images/osho zen/the-fool-oshozentarot-wallpaper.png
    - assets/images/osho zen/the-lovers-osho-zen.png
    - assets/images/osho zen/the-master-osho-zen.png
    - assets/images/osho zen/the-rebel-osho-zen-tarot.png
    - assets/images/osho zen/the-silence-osho-zen.png
    - assets/images/osho zen/three-of-clouds-osho-zen.png
    - assets/images/osho zen/three-of-fire-osho-zen.png
    - assets/images/osho zen/three-of-rainbows-osho-zen.png
    - assets/images/osho zen/three-of-water-osho-zen.png
    - assets/images/osho zen/thunderbolt-osho-zen.png
    - assets/images/osho zen/transformation-osho-zen.png
    - assets/images/osho zen/two-of-clouds-osho-zen.png
    - assets/images/osho zen/two-of-fire-zen.png
    - assets/images/osho zen/two-of-rainbow-osho-zen.png
    - assets/images/osho zen/two-of-water-osho-zen.png


  fonts:
    - family: Fo
      fonts:
        - asset: assets/fonts/fo1.ttf
        - asset: assets/fonts/fo2.ttf
        - asset: assets/fonts/fo3.ttf
        - asset: assets/fonts/fo4.ttf
        - asset: assets/fonts/fo5.ttf
        - asset: assets/fonts/fo7.ttf
        - asset: assets/fonts/fo8.ttf
        - asset: assets/fonts/fo9.ttf
        - asset: assets/fonts/fo10.ttf
        - asset: assets/fonts/fo11.ttf
        - asset: assets/fonts/fo12.ttf
        - asset: assets/fonts/fo13.ttf
        - asset: assets/fonts/fo14.ttf
        - asset: assets/fonts/fo15.ttf
        - asset: assets/fonts/fo16.ttf
        - asset: assets/fonts/fo17.ttf
        - asset: assets/fonts/fo18.ttf

