name: aurana
description: "spirit guide"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^5.3.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: 18.0.1
  timezone: ^0.9.4
  url_launcher: ^6.3.1
  http: ^1.3.0
  speech_to_text: ^7.0.0
  image_picker: ^0.8.7+3
  encrypt: ^5.0.3
  intl: ^0.18.0
  camera: ^0.11.1
  ar_flutter_plugin: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/tarot/
    - assets/images/parchment_background.png
    - assets/images/bg1.png
    - assets/images/bg2.png
    - assets/images/bg3.png
    - assets/images/bg4.png
    - assets/images/bg5.png
    - assets/images/bg6.png
    - assets/images/bg7.png
    - assets/images/bg8.png
    - assets/images/bg9.png
    - assets/images/bg10.png

  fonts:
    - family: Fo
      fonts:
        - asset: assets/fonts/fo1.ttf
        - asset: assets/fonts/fo2.ttf
        - asset: assets/fonts/fo3.ttf
        - asset: assets/fonts/fo4.ttf
        - asset: assets/fonts/fo5.ttf
        - asset: assets/fonts/fo7.ttf
        - asset: assets/fonts/fo8.ttf
        - asset: assets/fonts/fo9.ttf
        - asset: assets/fonts/fo10.ttf
        - asset: assets/fonts/fo11.ttf
        - asset: assets/fonts/fo12.ttf
        - asset: assets/fonts/fo13.ttf
        - asset: assets/fonts/fo14.ttf
        - asset: assets/fonts/fo15.ttf
        - asset: assets/fonts/fo16.ttf
        - asset: assets/fonts/fo17.ttf
        - asset: assets/fonts/fo18.ttf