name: aurana
description: "spirit guide"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^5.3.1
  shared_preferences: ^2.5.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  url_launcher: ^6.3.1
  http: ^0.13.6
  speech_to_text: ^7.0.0
  image_picker: ^1.1.2
  encrypt: ^5.0.3
  intl: ^0.20.2
  camera: ^0.10.0+4
  path_provider: ^2.0.14
  win32: ^5.5.3
  google_ml_kit: ^0.19.0 # Use the latest version available
  sqflite: ^2.2.0
  path: ^1.8.3
  fluttertoast: ^8.2.1
  share_plus: ^10.1.4
  flutter_animate: ^4.5.2
  confetti: ^0.7.0
  supabase_flutter: ^2.8.3
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.2.1
  font_awesome_flutter: ^10.4.0
  cached_network_image: ^3.2.3
  video_player: ^2.9.3
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  postgrest: ^2.1.0
  dart_openai: ^1.0.0
  audioplayers: ^5.2.0  # ✅ Add this line for sound playback
  flutter_launcher_icons: ^0.13.1
  in_app_purchase: ^3.1.5
  googleapis_auth: ^1.4.1
  swipable_stack: ^1.1.0
  shimmer: ^3.0.0
  geolocator: ^10.0.0
  geocoding: ^2.0.5
flutter_icons:
  android: true
  ios: false  # ✅ This prevents any iOS changes
  image_path: "assets/aurana.png"  # ✅ Change this to your icon path
  adaptive_icon_foreground: "assets/aurana.png"
  adaptive_icon_background: "#000000"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/tarot/
    - assets/images/parchment_background.png
    - assets/images/bg1.png
    - assets/images/bg2.png
    - assets/images/bg3.png
    - assets/images/bg4.png
    - assets/images/bg5.png
    - assets/images/bg6.png
    - assets/images/bg7.png
    - assets/images/bg8.png
    - assets/images/bg9.png
    - assets/images/bg10.png
    - assets/images/bg0.png
    - assets/images/27.png
    - assets/images/30.png
    - assets/images/serv1.png
    - assets/images/profile.png
    - assets/model.tflite
    - .env
    - assets/default_avatar.png
    - assets/sounds/card_flip.mp3
    - assets/media/splash.gif


  fonts:
    - family: Fo
      fonts:
        - asset: assets/fonts/fo1.ttf
        - asset: assets/fonts/fo2.ttf
        - asset: assets/fonts/fo3.ttf
        - asset: assets/fonts/fo4.ttf
        - asset: assets/fonts/fo5.ttf
        - asset: assets/fonts/fo7.ttf
        - asset: assets/fonts/fo8.ttf
        - asset: assets/fonts/fo9.ttf
        - asset: assets/fonts/fo10.ttf
        - asset: assets/fonts/fo11.ttf
        - asset: assets/fonts/fo12.ttf
        - asset: assets/fonts/fo13.ttf
        - asset: assets/fonts/fo14.ttf
        - asset: assets/fonts/fo15.ttf
        - asset: assets/fonts/fo16.ttf
        - asset: assets/fonts/fo17.ttf
        - asset: assets/fonts/fo18.ttf
