name: aurana
description: "spirit guide"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^5.3.1
  shared_preferences: ^2.0.17
  flutter_local_notifications: 18.0.1
  timezone: ^0.9.4
  url_launcher: ^6.3.1
  http: ^1.3.0
  speech_to_text: ^7.0.0
  image_picker: ^0.8.7+3
  encrypt: ^5.0.3
  intl: ^0.18.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.7.1
  google_sign_in: ^6.0.1
  cloud_firestore: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/tarot/
    - assets/images/parchment_background.png

  fonts:
    - family: CabinSketch
      fonts:
        - asset: assets/fonts/CabinSketch-Bold.ttf
          weight: 700
        - asset: assets/fonts/CabinSketch-Regular.ttf
          weight: 400
    - family: Whisper
      fonts:
        - asset: assets/fonts/Whisper-Regular.ttf
    - family: Chewy
      fonts:
        - asset: assets/fonts/Chewy-Regular.ttf