// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj2scxJHGb0zDRTj6uHpXY_DmH6Fap0So',
    appId: '1:960260575633:android:db690f24caa29920f34a30',
    messagingSenderId: '960260575633',
    projectId: 'aurana-b3436',
    storageBucket: 'aurana-b3436.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXq2a2Byej2FWsfjBvY0vRekR9IlFAMNg',
    appId: '1:960260575633:ios:cd510d2d78e5f9c6f34a30',
    messagingSenderId: '960260575633',
    projectId: 'aurana-b3436',
    storageBucket: 'aurana-b3436.firebasestorage.app',
    androidClientId: '960260575633-t1ost4tu9oo8fgjkd218glimh2eeajkf.apps.googleusercontent.com',
    iosClientId: '960260575633-udua2shdrns1ttquo9acs7ah0q675ve5.apps.googleusercontent.com',
    iosBundleId: 'com.kris.aurana',
  );
}